[build]
builder = "nixpacks"
buildCommand = "npm run build"
startCommand = "npm run start"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[service]
internal_port = 3001